### ISSUE TITLE
this file  is empty ，examples/fuse_gen.py

### ISSUE THREAD

**Issue by bohr** [YaoJiayi/CacheBlend#1]
examples/fuse_gen.py

**Comment by bohr** [comment]
file in examples are empty

**Comment by bohr** [comment]
@YaoJiayi

**Comment by YaoJiayi** [comment]
Thanks for the issue! The repo is still under construction. Sorry I don't have enough cycles for this this week. I'll try to update the code during the weekend or early next week.
