### ISSUE TITLE
CacheBlend for vLLM 0.6.0

### ISSUE THREAD

**Issue by jiangguochaoGG** [YaoJiayi/CacheBlend#12]
CacheBlend is truly impressive! I’m currently trying to migrate the logic of this repository to vLLM 0.6.0, but I’ve run into a challenging bug. Could you please advise on how to adapt CacheBlend’s logic to the new version of vLLM? Specifically, do I only need to modify `llama.py`, `xformers.py`, and `layer.py`, or is there more to consider?

**Comment by jiangguochaoGG** [comment]
Modify `model_runner.py` to change the logic of `compute_logits`.

**Comment by YaoJiayi** [comment]
Hi, hope you have solved the issues. We plan to integrate CacheBlend in to latest version of vllm in https://github.com/LMCache/LMCache
