### ISSUE TITLE
How KV cache is loaded in layer-by-layer fashion？

### ISSUE THREAD

**Issue by nata8noko** [YaoJiayi/CacheBlend#15]
Hello, thanks for the great work!

In the paper (https://arxiv.org/pdf/2405.16444v2), it is said that pre-computed KV cache is loaded (and also saved ?) in layer-by-layer manner and thus KV-loading delay can hide recompute delay.

I wonder how this can be implemented with LMCache, because it seems that all layers of KV cache are saved and loaded together if we use LMCache.
(I read a code around https://github.com/YaoJiayi/CacheBlend/blob/8c8e6450411590ecf1ec442b32f3b204fe602b97/vllm_blend/vllm/worker/model_runner.py#L284) 

It would be really appricated if you could let me know how the layer-by-layer KV-loading is implemented in CacheBlend, or will it be integrated into LMCache (lmcache-vllm) ?

**Comment by YaoJiayi** [comment]
Hi, thanks for the question! Yes, we are integrating the pipelining stuff into LMCache (likely to be in lmcache-vllm).

**Comment by nata8noko** [comment]
Thanks for the reply. Then I look forward to seeing CacheBlend integrated into LMCache.
