### ISSUE TITLE
examples文件是空的

### ISSUE THREAD

**Issue by zjjznw123** [YaoJiayi/CacheBlend#2]
数据是空的，代码也是空的，啥时候能看到

**Comment by YaoJiayi** [comment]
Sorry for the delay. Most of the integration is already there under the vllm_fuse folder. Currently I'm working on another project. Will prepare runnable scripts and data asap. Thanks for the understanding.

**Comment by zjjznw123** [comment]
没有入参，看不到数据的流向，期待早日更新
