### ISSUE TITLE
Can you share the code for KVCache to recalculate experimental data?

### ISSUE THREAD

**Issue by qiyuxinlin** [YaoJiayi/CacheBlend#4]
I was wondering about your use of Mistral-7B to reuse KVCache on 2WikiMQA and recompute less than 20% of the data to achieve performance without degradation.

**Comment by ahmedhannan** [comment]
Hello, Can you please get in touc? I'm having some issues in this and would like to seek your help.

**Comment by YaoJiayi** [comment]
Hi, the evaluation of musique dataset is uploded. We will add other datasets soon.
