### ISSUE TITLE
 According to the readme, there is an error when installing.

### ISSUE THREAD

**Issue by qiyuxinlin** [YaoJiayi/CacheBlend#5]
ImportError: /opt/conda/envs/CacheBlend/lib/python3.10/site-packages/vllm/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEESt8optionalINS2_10ScalarTypeEES6_INS2_6LayoutEES6_INS2_6DeviceEES6_IbES6_INS2_12MemoryFormatEE

**Comment by yifan1130** [comment]
Same problem here

**Comment by yifan1130** [comment]
Solved this bug by installing the torch == 2.2.1 xformers == 0.0.25, and revised the requirements.txt

**Comment by YaoJiayi** [comment]
Great, thanks a lot! There seems to be a similar discussion in the vllm repo: https://github.com/vllm-project/vllm/issues/2747
